import type { Metadata } from 'next'
import './globals.css'
import { Providers } from '@components/providers/providers'

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
